---
name: Molecoule for ansible
description: Just run molecule for test ansible role
author: Nikita Galkin

branding:
  icon: upload
  color: green

inputs:

  command:
    description: Command to pass to molecule ( e.g test, converge, prepare )
    required: true
    default: 'test'

runs:
  using: docker
  image: docker://uchiru/molecule-action:stable
  env:
    command: ${{ inputs.command }}
