---
name: Molecoule for ansible
description: Just run molecule for test ansible role
author: Nikita Galkin

branding:
  icon: upload
  color: green

inputs:

  command:
    description: Command to pass to molecule ( e.g test, converge, prepare )
    required: true
    default: 'test'

runs:
  using: docker
  image: docker://sysregistry.runit.cc/molecule-action:v1.4
  env:
    command: ${{ inputs.command }}
env:
    REGISTRY: sysregistry.runit.cc
    REGISTRY_USERNAME:     '${{ secrets.SYS_REGISTRY_USERNAME }}'
    REGISTRY_PASSWORD: '${{ secrets.SYS_REGISTRY_PASSWORD }}'
steps:
  - name: Setup registry credentials
    run: docker login $REGISTRY --username $REGISTRY_USERNAME --password $REGISTRY_PASSWORD
