name: Release
on:
  workflow_dispatch: {}
  push:
    branches: [master, main]
    paths-ignore: ['*.md', '.**']

jobs:
  bump:
    uses: uchiru/platform-gha-workflows/.github/workflows/bump.yml@master
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  build-push:
    runs-on: ubuntu-latest
    needs: bump
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Calculate metadata
        id: meta
        run: |
          img_name=${{ inputs.registry }}/${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}
          bumped_tag=${{ inputs.tag }}
          if [ ! -z $bumped_tag ]; then
            img_tag=$bumped_tag
          elif [ $GITHUB_REF_TYPE = "tag" ]; then
            img_tag=$GITHUB_REF_NAME
          else
            img_tag=$(echo ${GITHUB_REF_NAME} | tr -s '[:punct:]' '-')-${GITHUB_RUN_ATTEMPT}-${GITHUB_SHA:0:8}
          fi
          echo "name=$img_name" >> $GITHUB_OUTPUT
          echo "tag=$img_tag" >> $GITHUB_OUTPUT
          echo "New image name: $img_name:$img_tag"

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: uchiru/molecule-action:${{ steps.meta.outputs.tag }}

