name: Release
on:
  workflow_dispatch: {}
  push:
    branches: [master, main]
    paths-ignore: ['*.md', '.**']

jobs:
  bump:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.bump_step.outputs.tag }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'
    - name: Bump version and push tag
      id: bump_step
      uses: uchiru/bump-version-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true

  build-push:
     runs-on: ubuntu-latest
     needs: bump
     steps:
       - name: Checkout
         uses: actions/checkout@v3

       - name: Set up QEMU
         uses: docker/setup-qemu-action@v2

       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2

       - name: Login to Docker Hub
         uses: docker/login-action@v2
         with:
           username: ${{ secrets.DOCKERHUB_LOGIN }}
           password: ${{ secrets.DOCKERHUB_PASSWORD }}

       - name: Build and push
         uses: docker/build-push-action@v4
         with:
           push: true
           tags: uchiru/molecule-action:${{ needs.bump.outputs.tag }}
